[[redirects]]
  from = "/api/read.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/create.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/delete.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}