 [[redirects]]
  from = "/api/create.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
 [[redirects]]
  from = "/api/read.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
 [[redirects]]
  from = "/api/delete.php"
  to = "https://junior-dev-test-api.000webhostapp.com"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}